from tkinter import *
from tkinter import messagebox

def Instrucciones():
    window = Tk()
    window.title("INSTRUCCIONES DE USO")
    window.resizable(0,0)
    window.iconbitmap(r'ico/Icon.ico')
    Frame1 = Frame(window)
    Frame1.pack()
    string = '''
    PARA EL CORRECTO USO DE ESTA APLICACION SE DEBEN CONSIDERAR LOS SIGUIENTES PUNTOS.

    * SE DEBE CONECTAR A LA BASE DE DATOS QUE ESTA UBICADA EN LA MISMA DIRECCION QUE 
      LA APLICACION, POR LO QUE ANTES DE USAR EL PROGRAMA DEBE EJECUTAR LA ACCION 
      BBDD -> CONECTAR. 

    * SI EXISTE LA BASE DE DATOS AL MOMENTO DE CONECTAR YA SE PODRA USAR LA APLICACION, 
      EN CASO CONTRARIO, SE CREARA UN ARCHIVO .db QUE SERA UNA BASE DE DATOS NUEVA.

    * LOS TIPOS DE DATOS PARA CADA UNO DE LOS CUADROS DE TEXTO SON:
        -ID -> NUMERO ENTERO.
        -PRODUCTO -> TEXTO.
        -CONTENIDO NETO -> NUMERO DECIMAL.
        -CANTIDAD -> NUMERO ENTERO.
        -PRECIO -> NUMERO DECIMAL.
    
    * EN CASO DE NO RESPETAR LO ANTERIOR MENCIONADO, LA APLICACION LANZARA UN ERROR Y
      VACIARA LOS CUADROS DE TEXTO.

    * PARA QUE LOS BOTONES FUNCIONEN SE DEBEN LLENAR LOS SIGUIENTES CUADROS DE TEXTO:
        -AÑADIR -> TODOS LOS CUADROS DE TEXTO.
        -BUSCAR -> SOLO EL CUADOR DE TEXTO ID.
        -ELIMINAR -> SOLO EL CUADOR DE TEXTO ID.

    * PARA EL BOTON DE ACTUALIZAR SE NECESITA PRIMERO INGRESAR EL ID DEL REGISTRO EXISTENTE
      Y DESPUES SE PROCEDE A EDITAR TODOS LOS DEMAS CUADROS DE TEXTO PARA PODER USAR ESTE
      BOTON. 

    * EL ID NO SE PUEDE MODIFICAR DE NINGUNA MANERA.
    '''
    info = Label(Frame1, text=string, justify="left")
    info.grid(row=0,column=0, padx=10, pady=10)
    window.mainloop()