from tkinter import *
from tkinter import ttk
from tkinter import messagebox

def float_test(var):
    try:
        float(var)
        return True
    except:
        return False

def integer_test(var):
    try:
        int(var)
        return True
    except:
        return False

class App:
    def __init__(self):
        self.window = Tk()
        self.window.title("CRUD")
        self.window.resizable(0,0)

        self.MenuBarra = Menu(self.window)
        self.window.config(menu=self.MenuBarra)
        self.MainMenu = Menu(self.MenuBarra,tearoff=0)
        self.MainMenu.add_command(label="Salir",command=lambda: self.Exit())
        self.Limpiar = Menu(self.MenuBarra,tearoff=0)
        self.Limpiar.add_command(label="Limpiar Campos",command=lambda: self.Clear())
        self.Ayuda = Menu(self.MenuBarra,tearoff=0)
        self.Ayuda.add_command(label="Acerca de...",command=lambda: self.About())
        self.MenuBarra.add_cascade(label="CRUD", menu=self.MainMenu)
        self.MenuBarra.add_cascade(label="Limpiar", menu=self.Limpiar)
        self.MenuBarra.add_cascade(label="Ayuda", menu=self.Ayuda)

        self.ntb1 = ttk.Notebook(self.window)
        self.ntb1.pack()

        self.ID_Articulo1 = StringVar()
        self.Articulo1 = StringVar()
        self.Precio1 = StringVar()
        self.Cantidad1 = StringVar()
        self.Pag1 = Frame(self.ntb1)
        self.Pag1.pack()
        self.lb1 = Label(self.Pag1,text="ID_Articulo:")
        self.lb1.config(font=("Calibri",11))
        self.lb1.grid(row=0,column=0,sticky=E,padx=5,pady=5)
        self.lb2 = Label(self.Pag1,text="Articulo:")
        self.lb2.config(font=("Calibri",11))
        self.lb2.grid(row=1,column=0,sticky=E,padx=5,pady=5)
        self.lb3 = Label(self.Pag1,text="Precio: $")
        self.lb3.config(font=("Calibri",11))
        self.lb3.grid(row=2,column=0,sticky=E,padx=5,pady=5)
        self.lb4 = Label(self.Pag1,text="Cantidad:")
        self.lb4.config(font=("Calibri",11))
        self.lb4.grid(row=3,column=0,sticky=E,padx=5,pady=5)
        self.et1 = Entry(self.Pag1,width=40, textvariable=self.ID_Articulo1)
        self.et1.config(font=("Calibri",11))
        self.et1.grid(row=0,column=1,sticky=W,padx=5,pady=5)
        self.et2 = Entry(self.Pag1,width=40,textvariable=self.Articulo1)
        self.et2.config(font=("Calibri",11))
        self.et2.grid(row=1,column=1,sticky=W,padx=5,pady=5)
        self.et3 = Entry(self.Pag1,width=40,textvariable=self.Precio1)
        self.et3.config(font=("Calibri",11))
        self.et3.grid(row=2,column=1,sticky=W,padx=5,pady=5)
        self.et4 = Entry(self.Pag1,width=40,textvariable=self.Cantidad1)
        self.et4.config(font=("Calibri",11))
        self.et4.grid(row=3,column=1,sticky=W,padx=5,pady=5)
        self.b1 = Button(self.Pag1,text="Registrar",width=48)
        self.b1.config(font=("Calibri",11))
        self.b1.grid(row=4,column=0,columnspan=2,padx=5,pady=5)
        self.ntb1.add(self.Pag1,text="Create")

        self.ID_Articulo2 = StringVar()
        self.Pag2 = Frame(self.ntb1)
        self.Pag2.pack()
        self.lb5 = Label(self.Pag2,text="ID_Articulo:")
        self.lb5.config(font=("Calibri",11))
        self.lb5.grid(row=0,column=0,sticky=E,padx=5,pady=5)
        self.et5 = Entry(self.Pag2,width=40,textvariable=self.ID_Articulo2)
        self.et5.config(font=("Calibri",11))
        self.et5.grid(row=0,column=1,sticky=W,padx=5,pady=5)
        self.b2 = Button(self.Pag2,text="Buscar",width=48)
        self.b2.config(font=("Calibri",11))
        self.b2.grid(row=1,column=0,columnspan=2,padx=5,pady=5)
        self.lb6 = Label(self.Pag2,text="Articulo:")
        self.lb6.config(font=("Calibri",11))
        self.lb6.grid(row=2,column=0,sticky=E,padx=5,pady=5)
        self.lb7 = Label(self.Pag2,text="Precio: $")
        self.lb7.config(font=("Calibri",11))
        self.lb7.grid(row=3,column=0,sticky=E,padx=5,pady=5)
        self.lb8 = Label(self.Pag2,text="Cantidad:")
        self.lb8.config(font=("Calibri",11))
        self.lb8.grid(row=4,column=0,sticky=E,padx=5,pady=5)
        self.et6 = Entry(self.Pag2,width=40,state=DISABLED)
        self.et6.config(font=("Calibri",11))
        self.et6.grid(row=2,column=1,sticky=W,padx=5,pady=5)
        self.et7 = Entry(self.Pag2,width=40,state=DISABLED)
        self.et7.config(font=("Calibri",11))
        self.et7.grid(row=3,column=1,sticky=W,padx=5,pady=5)
        self.et8 = Entry(self.Pag2,width=40,state=DISABLED)
        self.et8.config(font=("Calibri",11))
        self.et8.grid(row=4,column=1,sticky=W,padx=5,pady=5)
        self.ntb1.add(self.Pag2,text="Read")
        
        self.ID_Articulo3 = StringVar()
        self.Articulo3 = StringVar()
        self.Precio3 = StringVar()
        self.Cantidad3 = StringVar()
        self.Pag3 = Frame(self.ntb1)
        self.Pag3.pack()
        self.lb9 = Label(self.Pag3,text="ID_Articulo:")
        self.lb9.config(font=("Calibri",11))
        self.lb9.grid(row=0,column=0,sticky=E,padx=5,pady=5)
        self.et9 = Entry(self.Pag3,width=40,textvariable=self.ID_Articulo3)
        self.et9.config(font=("Calibri",11))
        self.et9.grid(row=0,column=1,sticky=W,padx=5,pady=5)
        self.b3 = Button(self.Pag3,text="Buscar",width=48)
        self.b3.config(font=("Calibri",11))
        self.b3.grid(row=1,column=0,columnspan=2,padx=5,pady=5)
        self.lb10 = Label(self.Pag3,text="Articulo:")
        self.lb10.config(font=("Calibri",11))
        self.lb10.grid(row=2,column=0,sticky=E,padx=5,pady=5)
        self.lb11 = Label(self.Pag3,text="Precio: $")
        self.lb11.config(font=("Calibri",11))
        self.lb11.grid(row=3,column=0,sticky=E,padx=5,pady=5)
        self.lb12 = Label(self.Pag3,text="Cantidad:")
        self.lb12.config(font=("Calibri",11))
        self.lb12.grid(row=4,column=0,sticky=E,padx=5,pady=5)
        self.et10 = Entry(self.Pag3,width=40,textvariable=self.Articulo3)
        self.et10.config(font=("Calibri",11))
        self.et10.grid(row=2,column=1,sticky=W,padx=5,pady=5)
        self.et11 = Entry(self.Pag3,width=40,textvariable=self.Precio3)
        self.et11.config(font=("Calibri",11))
        self.et11.grid(row=3,column=1,sticky=W,padx=5,pady=5)
        self.et12 = Entry(self.Pag3,width=40,textvariable=self.Cantidad3)
        self.et12.config(font=("Calibri",11))
        self.et12.grid(row=4,column=1,sticky=W,padx=5,pady=5)
        self.b4 = Button(self.Pag3,text="Actualizar",width=48)
        self.b4.config(font=("Calibri",11))
        self.b4.grid(row=5,column=0,columnspan=2,padx=5,pady=5)
        self.ntb1.add(self.Pag3,text="Update")

        self.ID_Articulo4 = StringVar()
        self.Pag4 = Frame(self.ntb1)
        self.Pag4.pack()
        self.lb13 = Label(self.Pag4,text="ID_Articulo:")
        self.lb13.config(font=("Calibri",11))
        self.lb13.grid(row=0,column=0,sticky=E,padx=5,pady=5)
        self.et13 = Entry(self.Pag4,width=40,textvariable=self.ID_Articulo4)
        self.et13.config(font=("Calibri",11))
        self.et13.grid(row=0,column=1,sticky=W,padx=5,pady=5)
        self.b5 = Button(self.Pag4,text="Eliminar",width=48)
        self.b5.config(font=("Calibri",11))
        self.b5.grid(row=1,column=0,columnspan=2,padx=5,pady=5)
        self.ntb1.add(self.Pag4,text="Delete")

        self.window.mainloop()
    def Exit(self):
        valor=messagebox.askquestion("Salir","¿Desea salir de la aplicacion?")
        if valor == "yes":
            self.window.destroy()
    def About(self):
        messagebox.showinfo("ACERCA DE...","Version: 1.0\nDesarrollador: Lenin Eduardo Franco Aguilar\nEscuela: ESCOM IPN")
    def Clear(self):
        self.ID_Articulo1.set("")
        self.ID_Articulo2.set("")
        self.ID_Articulo3.set("")
        self.ID_Articulo4.set("")
        self.Articulo1.set("")
        self.Articulo3.set("")
        self.Precio1.set("")
        self.Precio3.set("")
        self.Cantidad1.set("")
        self.Cantidad3.set("")


if __name__ == "__main__":
    App()